In [7]:
import numpy as np

In [8]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'PackageLoader',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__doc__',
 '__file__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_distributor_init',
 '_globa

In [14]:
a=[1,2,3,4,5,6,7,8,9]

In [90]:
b=np.array(a)

In [18]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
b.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
c=np.arange(100)

In [25]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
d=c.reshape(10,10)

In [30]:
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
list1=[111,222,333]
tuple1=(444,555,666)

seq1=tuple1

print(seq1)
print(len(seq1),type(seq1)); print()

arr1=np.array(seq1,dtype=np.int64)
print(arr1);print(type(arr1)); print()

(444, 555, 666)
3 <class 'tuple'>

[444 555 666]
<class 'numpy.ndarray'>



In [84]:
print("shape",arr1.shape)

shape (3,)


In [34]:
print("ndim",arr1.ndim)

ndim 1


In [37]:
print("stride",arr1.strides)

stride (8,)


In [39]:
print("itemsize",arr1.itemsize)

itemsize 8


In [42]:
print("arr count",arr1.size)

arr count 3


In [45]:
print("total memory occupied",arr1.size*arr1.itemsize)

total memory occupied 24


In [47]:
print(arr1[0],arr1[1],arr1[2])

444 555 666


In [61]:
list1=[111,222,333]
list2=[444,555,666]

arr1=np.array(list1,dtype=np.int32)
arr2=np.array(list2,dtype=np.int32)
arr3=arr1+arr2

print(arr1)
print(arr2)
print(arr3)

[111 222 333]
[444 555 666]
[555 777 999]


In [63]:
arr1.strides

(4,)

In [65]:
list4=[[11,21,31],[41,51,61],[71,81,91],[101,111,121]]


In [67]:
list4

[[11, 21, 31], [41, 51, 61], [71, 81, 91], [101, 111, 121]]

In [77]:
print(len(list4),type(list4)); print()

4 <class 'list'>



In [104]:
arr4=np.array(list4,dtype=np.int64)
print(len(arr4),type(arr4)); print()

4 <class 'numpy.ndarray'>



In [105]:
arr4

array([[ 11,  21,  31],
       [ 41,  51,  61],
       [ 71,  81,  91],
       [101, 111, 121]], dtype=int64)

In [108]:
print("shape",arr4.shape)
print("ndim",arr4.ndim)
print("stride",arr4.strides)
print("itemsize",arr4.itemsize)
print("arr count",arr4.size)
print("total memory occupied",arr4.size*arr4.itemsize)

print(arr4[0])
print(arr4[1][2])
print(arr4[2,2])
print(type(arr4[2,2]))

shape (4, 3)
ndim 2
stride (24, 8)
itemsize 8
arr count 12
total memory occupied 96
[11 21 31]
61
91
<class 'numpy.int64'>


In [120]:
z=np.zeros((3,2),dtype=int)
print(type(z[1,1]))

<class 'numpy.int32'>


In [117]:
y=np.ones((3,2),dtype=int)
y

array([[1, 1],
       [1, 1],
       [1, 1]])

In [145]:
list5=[[11,21,31],[41,51,61],[71,81,91],[101,111,121]]
list6=[[12,22,32],[42,52,62],[72,82,92],[102,112,122]]


arr5=np.array(list5)
arr6=np.array(list6)
arr7=arr5+arr6

print(arr5)
print(arr6)
print(arr7)

[[ 11  21  31]
 [ 41  51  61]
 [ 71  81  91]
 [101 111 121]]
[[ 12  22  32]
 [ 42  52  62]
 [ 72  82  92]
 [102 112 122]]
[[ 23  43  63]
 [ 83 103 123]
 [143 163 183]
 [203 223 243]]


In [125]:
c=np.transpose(arr7)
c

array([[ 23,  83, 143, 203],
       [ 43, 103, 163, 223],
       [ 63, 123, 183, 243]])

In [192]:
list9=[[11,21,31,25],[41,51,61,65],[71,81,91,58]]
list10=[[12,22,32],[42,52,62],[72,82,92],[102,112,122]]


arr9=np.array(list9)
arr10=np.array(list10)
arr11=arr9.dot(arr10)

print(arr9)
print(arr10)
print(arr11)

[[11 21 31 25]
 [41 51 61 65]
 [71 81 91 58]]
[[ 12  22  32]
 [ 42  52  62]
 [ 72  82  92]
 [102 112 122]]
[[ 5796  6676  7556]
 [13656 15836 18016]
 [16722 19732 22742]]


In [196]:
b=arr.reshape(6,4)
print(b)

[[11 21 31 12]
 [22 32 13 23]
 [43 14 24 34]
 [15 25 35 16]
 [26 36 17 27]
 [37 18 28 38]]


In [198]:
c=arr.reshape(2,12)
print(c)

[[11 21 31 12 22 32 13 23 43 14 24 34]
 [15 25 35 16 26 36 17 27 37 18 28 38]]


In [201]:
d=arr.reshape(2,3,4)
print(d)
print(d.shape)

[[[11 21 31 12]
  [22 32 13 23]
  [43 14 24 34]]

 [[15 25 35 16]
  [26 36 17 27]
  [37 18 28 38]]]
(2, 3, 4)


In [225]:
list3d=[ [[111,121],[141,151],[171,181]],
         [[211,221],[241,251],[271,281]],
         [[311,321],[341,351],[371,381]],
         [[411,421],[441,451],[471,481]],
       ]

print(list3d)
arr1=np.array(list3d,dtype=np.int32)
arr1=arr1.reshape(4,3,2);print()
print(arr1);print(type(arr1));print()

print("shape",arr1.shape)
print("ndim",arr1.ndim)
print("stride",arr1.strides)
print("itemsize",arr1.itemsize)
print("arr count",arr1.size)
print("total memory occupied",arr1.size*arr1.itemsize)

print(arr1[0][1][0])
y=arr1[[0,1,2],[0,1,0]]# it will take (0,0),(1,1),(2,0) columns sine i dint give the depth values
y1=arr1[[0,1,2],[0,1,0],[0,0,0]] #here depth values (0,0,0) is given
print(y)
print(y1)

[[[111, 121], [141, 151], [171, 181]], [[211, 221], [241, 251], [271, 281]], [[311, 321], [341, 351], [371, 381]], [[411, 421], [441, 451], [471, 481]]]

[[[111 121]
  [141 151]
  [171 181]]

 [[211 221]
  [241 251]
  [271 281]]

 [[311 321]
  [341 351]
  [371 381]]

 [[411 421]
  [441 451]
  [471 481]]]
<class 'numpy.ndarray'>

shape (4, 3, 2)
ndim 3
stride (24, 8, 4)
itemsize 4
arr count 24
total memory occupied 96
141
[[111 121]
 [241 251]
 [311 321]]
[111 241 311]


In [233]:
ar2=np.arange(2,20,2)
print(ar2)
print()

ar3=np.arange(2.1,5.1,0.25)
print(ar3)
print()

ar4=np.arange(2.1,5.1,0.25,float)
print(ar4)
print()

ar5=np.arange(2,18,2).reshape(2,4)
print(ar5)
print()

[ 2  4  6  8 10 12 14 16 18]

[2.1  2.35 2.6  2.85 3.1  3.35 3.6  3.85 4.1  4.35 4.6  4.85]

[2.1  2.35 2.6  2.85 3.1  3.35 3.6  3.85 4.1  4.35 4.6  4.85]

[[ 2  4  6  8]
 [10 12 14 16]]



In [235]:
list1=[[11,22,33],[44,55,66],[77,88,99]]
arr1=np.array(list1)
print(arr1)
print()

arr1+=1
print(arr1)
print('\n')
print()

arr1 *=2
print(arr1)
print()

[[11 22 33]
 [44 55 66]
 [77 88 99]]

[[ 12  23  34]
 [ 45  56  67]
 [ 78  89 100]]



[[ 24  46  68]
 [ 90 112 134]
 [156 178 200]]



In [237]:
#slicing
list2d= [  [11,21,31],
           [41,51,61],
           [71,81,91],
           [101,111,121]
        ]

x=np.array(list2d)

print(x)
print(x.shape)
print('\n')

z=x[1:4,1:3]#from row 1 - 4, and column 1-3
print("After slicing our array becomes")
print(z)
print('\n')

y=x[1:4,[0,1]]
print("after slicing individual index for columns")
print(y)

[[ 11  21  31]
 [ 41  51  61]
 [ 71  81  91]
 [101 111 121]]
(4, 3)


After slicing our array becomes
[[ 51  61]
 [ 81  91]
 [111 121]]


after slicing individual index for columns
[[ 41  51]
 [ 71  81]
 [101 111]]


In [247]:
n1=np.empty((3,2),dtype=np.int16)
print(n1)
print()
n2=np.ones((3,4))
print(n2)
print()
n3=np.zeros((2,3,4),dtype=np.int16)
print(n3)
print()
n4=np.full((2,2),5)
print(n4)
print()
n5=np.random.random((2,2))
print(n5)
print()
n6=np.identity((3))
print(n6)
print()
n7=np.eye(4,k=1)
print(n7)
print()# from k(column) it will print 1 in identity manner

print(n1.itemsize)

[[257 257]
 [257 257]
 [257 257]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]

[[5 5]
 [5 5]]

[[0.16500694 0.55818575]
 [0.64846827 0.92655164]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

2


In [248]:
help(np.empty)

Help on built-in function empty in module numpy.core.multiarray:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Ret

In [250]:
type(np)

module

In [252]:
type(np.random)

module

In [254]:
type(np.random.random)

builtin_function_or_method

In [272]:
import numpy as np

def create_np_array(r=3,c=4,d=2):
    x=np.random.randint(25,size=(r,c,d))
    return x

z=create_np_array(2,3,2)
print(z)
print(z.shape)

print("odd numbers are")
print(z[z%2 != 0])
print()
print(z[z>20])

x=z[z>15]
print(x)
print(type(x))
print(x.shape)

[[[ 0  9]
  [ 3  9]
  [ 8  3]]

 [[ 7  6]
  [23  3]
  [ 8 10]]]
(2, 3, 2)
odd numbers are
[ 9  3  9  3  7 23  3]

[23]
[23]
<class 'numpy.ndarray'>
(1,)


In [274]:
import random
x=random.randint(2,4)
print(x)

3


In [276]:
#linspace
print(np.linspace(1,10))
print('\n')
print(np.linspace(1,10,10))
print('\n')
print(np.linspace(1,10,10,endpoint=False))
print('\n')


[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]




In [279]:
help(np.linspace)

Help on function linspace in module numpy.core.function_base:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    Parameters
    ----------
    start : scalar
        The starting value of the sequence.
    stop : scalar
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is the last sample. Otherwise, it is not included.
        Default is True.
    retstep : bo

In [282]:
a=np.arange(2*3*4).reshape(2,3,4)

print(a)
print(a.shape)
print()

print("swap 0,2")
a1=np.swapaxes(a,0,2)
print(a1)
print(a1.shape)
print(a1.strides)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)

swap 0,2
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
(4, 3, 2)
(4, 16, 48)


In [2]:
#looping into an array
a=np.arange(0,60,5)
a=a.reshape(3,4)
print(a)
print()

print(":iterating array is:")
for x in np.nditer(a):
      print(x)
print()
      
#transpose array
b=a.T
print(b)
print("iterating array is :")
for x in np.nditer(b):
      print(x)
print()
      

NameError: name 'np' is not defined