# Importing the numpy package 


In [23]:
import numpy as np
myarr = np.array([1,2,3,4,5])
print(myarr)

[1 2 3 4 5]


## Note : Arrays can store elemements of the same type


# Advantages of array in numpy 
Uses less space and its faster in computation 


# q)Lets check the size of an integer type in Python 

In [24]:
import sys 
b  = 10
sys.getsizeof(b)

28

# q) Lets check the size of an empty list in Python

In [25]:
myl = []
sys.getsizeof(myl)


64

# q Lets add an item to the list and check the size 


In [ ]:
myl = [1]
sys.getsizeof(myl)

## Note : Every item in the list would occupy 8 bytes 

# q)Lets create a list of 100 elements 

In [26]:
myl=list(range(1,100))
print(myl)
type(myl)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


list

# q)Lets now check the size of the entire  list 


In [27]:
size_l = sys.getsizeof((myl[1])*len(myl))
print(size_l)


28


## Note : getsizeof(myl[1]) would give the size of one element of the list in bytes 



# q)Now lets create an array of 100 elements and check the size of the array 


In [28]:
myar = np.arange(100)
print(myar)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# q)How to find out the count of number of elements in an array


In [29]:
myar.size


100

# q)How to find the size (memory occupied) by every item in an array 


In [30]:
print(myar.itemsize)


4


# Now we need to multiple the lenght of the array with the #memory occupied by each array element to get the total 
# memory occupied by the entire array elements. 



In [31]:
size_a =  (myar.size)*(myar.itemsize)
print(size_a)


400


# Now compare how much memory does an array and list occupy (scroll up and compare with that of the list)


# q)How to verify that numpy arrays are faster than the python lists 


In [32]:
import sys
import time
import numpy as np 

def list_add(l1,l2):
 i=0
 for a in l2:
  l1[i]=l1[i]+a
  i=i+1


count = 10000
l1=list(range(count))
l2=list(range(count))

start=time.time()
list_add(l1,l2)
end=time.time()

elapsed = 1000*(end-start)
print("List addition time is ",elapsed)

a1 = np.arange(count)
a2 = np.arange(count)

start=time.time()
a3=a1+a2
end=time.time()

elapsed = 1000*(end-start)
print("Array addition time is ",elapsed)


List addition time is  3.000020980834961
Array addition time is  0.0


# In class lab exercise : 
Modify the above program to perform a slightly complex operation on a larger data set to observe the time difference. 


In [36]:
import sys
import time
import numpy as np 

def list_add(l1,l2):
 i=0
 for a in l2:
  l1[i]=l1[i]+a
  i=i+1


count = 10000
l1=list(range(count))
l2=list(range(count))

start=time.time()
list_add(l1,l2)
end=time.time()

start1=time.time()
del(l1)
end1=time.time()

elapsed = 1000*(end-start)
print("List addition time is ",elapsed)

elapsed1 = 1000*(end1-start1)
print("List deletion time is ",elapsed1)

a1 = np.arange(count)
a2 = np.arange(count)

start=time.time()
a3=a1+a2
end=time.time()

elapsed = 1000*(end-start)
print("Array addition time is ",elapsed)


List addition time is  2.0003318786621094
List deletion time is  0.9999275207519531
Array addition time is  0.0


# q)Demonstration of arithmatic operations on arrays 

Adding 2 arrays, 
Subrtacting 2 arrays 
Mul 
Div 


In [2]:
import numpy as np
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[7,8,9],[10,11,12]])
C=np.array([[13,14],[16,17],[19,20]])

add=A+B
print(add)
print()

sub=A-B
print(sub)
print()

Div=B/A
print(Div)
print()

Mul=A.dot(C)
print(Mul)
print()




[[ 8 10 12]
 [14 16 18]]

[[-6 -6 -6]
 [-6 -6 -6]]

[[7.  4.  3. ]
 [2.5 2.2 2. ]]

[[102 108]
 [246 261]]



# q)Creating a 2 dimensional array 


In [31]:
import numpy as np 
a = np.array([[1,2],[3,4]])
print(a)
a.ndim #The ndim will print the dimensionality of the array i.e 1 dimentional or 2 dimensional 


[[1 2]
 [3 4]]


2

# q)How to count the number of elements in any array 


In [3]:
print(a.size) 
print("shape =",a.shape) # would print how many rows and cols are there in the array 



4
shape = (2, 2)


# q) Lets see another example of using the shape function

In [4]:
a=np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

# q)Reshaping an array 


In [5]:
b = a.reshape((2,3))
b.shape
print(b)


[[1 2 3]
 [4 5 6]]


# q)Creating a zero value array 


In [6]:
a = np.zeros( (2,3) )   #will result in creating a 2 row and 3 col array, filled with zeroes 
print(a)

b = np.ones((2,3)) #This will create an array with value 1's 
print(b)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


# q)Using the arange function to create arrays 


In [7]:
a = np.arange(5)
print(a)


[0 1 2 3 4]


# q) Understanding the ravel function,its used to convert an N dimensional array into a 1 dimensional array 


In [19]:
b=np.array([[1,2],[3,4]])
a = b.ravel()
print(a)
type(a)

[1 2 3 4]


numpy.ndarray

# q)Finding out the min and max element from an array 


In [4]:
b=np.array([[1,2],[3,4]])
print("min of b is ",b.min())
print("max of b is ",b.max())

# Note: try the built in function b.sum()


min of b is  1
max of b is  4


# In class lab exercise  : 
Program a code snippet develop a custom user defined function to find out the min and max element from an 2 by 3 array or elements 
as shown below 

1 2
3 4
5 6 

Hint : U may use the ravel function to flatten it out and then work on finding the min and max elements from the array 
Note : U are not supposed to use the min or max built in function 


In [438]:
Arr=np.array([1,2,45,42,5,6]).reshape(2,3)
print("The array is ")
print(Arr)
print()
Arr1=Arr.ravel()
print("ravel array is :")
print(Arr1)
print()
while np.any(Arr1[:-1] > Arr1[1:]):
        np.random.shuffle(Arr1)
print("the sorted array is")
print(Arr1)
print()
print("the min is :",Arr1[0])
print()
print("the max is :",Arr1[-1])

The array is 
[[ 1  2 45]
 [42  5  6]]

ravel array is :
[ 1  2 45 42  5  6]

the sorted array is
[ 1  2  5  6 42 45]

the min is : 1

the max is : 45


# q)Operations on arrays (Addition, subtraction and multiplication is possible)


In [10]:
a=np.ones((2,2))
b=np.ones((2,2))
print(a)
print(b)
c = a+b
d = a-b
e = a*b
print("addition result follows\n\n:",c)
print("subtraction result follows\n \n :",d)
print("multiplication result follows\n \n :",e)


[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
addition result follows

: [[2. 2.]
 [2. 2.]]
subtraction result follows
 
 : [[0. 0.]
 [0. 0.]]
multiplication result follows
 
 : [[1. 1.]
 [1. 1.]]


# Slicing python lists 


In [11]:
l = [1,2,3,4,5]
l[2:4]


[3, 4]

# Similar kind of slicing is possible on Python arrays 


In [12]:
d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d2)

print(d2[0,0]) #This would print the element from 0th row and 0th column i.e 1 
print(d2[1,1]) #This would print the element from 0th row and 0th column i.e 5 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
5


# 1 2 3
# 4 5 6
# 7 8 9
# q)How to interpret the below statement with respect to the above 3 by 3 array



In [13]:
print(d2[0:2,2]) #would print [3 6] 
# [0:2,2] would translate to [(0,1),2] i.e to print the row 0 and row 1 elements of column 2 which is 3,6


[3 6]


In [14]:
print(d2[:,0:2]) # Print all the row elements from col 0 and col 1


[[1 2]
 [4 5]
 [7 8]]


# q)Iterating the array using for loops 

1 2 3
4 5 6
7 8 9

The array d2 contains the above elements

In [33]:
d2=[1,2,3,4,5,6,7,8,9]
for row in d2:
    print(row) 


1
2
3
4
5
6
7
8
9


# q)Conditional statements on arrays 


In [16]:
ca = np.arange(9).reshape(3,3)
print("The original array is \n" ,ca)

con = ca > 5 

print(" \nThe boolean array after the conditional statement is applied \n")
print(con)

ca[con] # The boolean TRUE/FALSE array is now the index and print only the numbers satisfying the the > 5 condition 


The original array is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
 
The boolean array after the conditional statement is applied 

[[False False False]
 [False False False]
 [ True  True  True]]


array([6, 7, 8])

# In class lab exercise : 
To create an array with 100 elements (M,N is 5,10) anf filter only those elements between than 75 and 100 and create a new array with 5 rows and 5 cols 


In [355]:
a=np.arange(1,101).reshape(10,10)
Arr=[]
print("array with 100 elemets is :")
print(a)
print()
b=[a[i][j] for i in range(10) for j in range(10)]
for i in b:
    if i>75:
        Arr.append(i)
print("The new array with 5 rows and 5 columns is :")
NewArr=np.array(Arr).reshape(5,5)
print(NewArr)

array with 100 elemets is :
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

The new array with 5 rows and 5 columns is :
[[ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]


# q)Replacing all the elements of an array which is greater than 4 with zero 


In [17]:
ca = np.arange(9).reshape(3,3)
print("The original array is : \n", ca)

con = ca > 4
ca[con]=0
print("\n",ca) 



The original array is : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 4 0]
 [0 0 0]]


# q)Taking a 1 dimensional array and reshaping it to a 2 dimensional array 


In [18]:
newa = np.arange(10).reshape(2,5)
newb = np.arange(10,20).reshape(2,5)

print(newa)
print(newb)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


# understanding stacking operations on an array 


In [19]:
newc=np.vstack((newa,newb))  # vstack is for vertical stacking and similarly hstack can be used too

print(newc)
type(newc)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


numpy.ndarray

# q)We can split a large arrays into smaller arrays 


In [20]:
biga = np.arange(60).reshape(6,10)
print(biga)
biga.shape

sma = np.hsplit(biga,2)  #  sma is a list consisting of 3 smaller arrays 
print(sma[0])
print(sma[1])



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]
 [55 56 57 58 59]]


# In class lab exercise  :  
Demonstrate using a code snippet to split the above biga into 3 smaller arrays using vsplit


In [23]:
biga = np.arange(60).reshape(6,10)
print(biga)
biga.shape

sma = np.vsplit(biga,3)  #  sma is a list consisting of 3 smaller arrays 
print()
print("the 3 smaller arrays after split are :")
print()
print(sma[0])
print()
print(sma[1])
print()
print(sma[2])



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]

the 3 smaller arrays after split are :

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

[[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


# Suppose you have array of 4 rows and 4 cols like the one shown below 
1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16

# In class lab exercise  :  -
Develop a code snippet to print only the right diagonal elements i.e 1, 6, 11, 16 
Hint : U need to use loops 


In [6]:
import numpy as np
A=np.arange(1,17).reshape(4,4)
print(A)
print()
A=[A[i][j] for i in range(4) for j in range(4)]
print("the right diagonals are :")
print(A[::5])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

the right diagonals are :
[1, 6, 11, 16]


# In class lab exercise :
Modify the above program to print the left diagonal elements i.e 4,7,10,13


In [317]:
A=np.arange(1,17).reshape(4,4)
print(A)
print()
A=[A[i][j] for i in range(4) for j in range(4)]
print("the left diagonals are :")
print(A[3:-1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

the left diagonals are :
[4, 7, 10, 13]


# In class lab exercise WAP : 
Take N elments into a function, the function must be able to generate a zero array of an appropriate dimension and populate the N elements as the right diagonal elements of the array. 


In [35]:
z=np.zeros((4,4),dtype=int)
print("zero array of dimension 4*4 :")
print(z)
print()
z=[z[i][j] for i in range(4) for j in range(4)]
z[::5]=[1,2,3,4]
a=np.array(z).reshape(4,4)
print("populating the N elements as the right diagonal elements of the array :")
print(a)
    


zero array of dimension 4*4 :
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

populating the N elements as the right diagonal elements of the array :
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# *************Take home weekend group assignment************

WAP to solve the below sudoku 

0 4 0 1
3 0 4 0
1 0 0 4
0 2 1 0 

The zero's represent empty cells. 



Note : Do not use the readily available algorithms to solve the sudoku problems. Instead, develop your custom code to solve only the above problem. Each group should choose a different sudoku problem which is at least 4 by 4 and above.   

 



In [8]:
Sudoku=np.array([[0,2,1,0],[1,0,0,3],[4,0,3,0],[0,2,4,0]])
z1=[]
sum=0
print(Sudoku)
S=Sudoku.T
z=[Sudoku[i][j] for i in range(4) for j in range(4)]
z1=z[:4]
print(z1)
for k in z1:
    if k==0:
        k=1
    print(k)
    sum+=k
print(z1[0],z1[1],z1[2],z1[3])
sum1=z1[0]+z1[1]+z1[2]+z1[3]
print(sum1)
print(sum)
    
print(z)
z2=[S[i][j] for i in range(4) for j in range(4)]
print(z2)

    

[[0 2 1 0]
 [1 0 0 3]
 [4 0 3 0]
 [0 2 4 0]]
[0, 2, 1, 0]
1
2
1
1
0 2 1 0
3
5
[0, 2, 1, 0, 1, 0, 0, 3, 4, 0, 3, 0, 0, 2, 4, 0]
[0, 1, 4, 0, 2, 0, 0, 2, 1, 0, 3, 4, 0, 3, 0, 0]


In [9]:
#sudoku
import numpy as np

c=[[0,4,0,1],[3,0,4,0],[1,0,0,4],[0,2,1,0]]
matrix=np.array(c)
print(matrix)

def mat(lis):
    for lis_1 in lis:
        for row in range(0,4):
            for col in range(0,4):
                if lis_1 not in matrix[row] and lis_1 not in matrix[:,col]:
                    if matrix[row,col]==0:
                        matrix[row,col]=lis_1
    return matrix
lis=list(range(1,5))
print(mat(lis))

[[0 4 0 1]
 [3 0 4 0]
 [1 0 0 4]
 [0 2 1 0]]
[[2 4 3 1]
 [3 1 4 2]
 [1 3 2 4]
 [4 2 1 3]]
