In [1]:
#lcm
def lcm(a,b):
    if(a>b):
        min1=a
    else:
        min1=b
    while(1):
        if(min1%a==0 and min1%b==0):
            break
        min1=min1+1
    return min1


num1 = int(input("Enter first number: "))  
num2 = int(input("Enter second number: "))  
print('The LCM of ',num1,' and ',num2 ,'is ',lcm(num1,num2))

Enter first number: 5
Enter second number: 12
The LCM of  5  and  12 is  60


In [1]:
#hcf
def computeHCF(x, y):

# choose the smaller number
    if x > y:
        smaller = y
    else:
        smaller = x
    for i in range(1, smaller+1):
        if((x % i == 0) and (y % i == 0)):
            hcf = i
            
    return hcf

x = int(input("Enter first number: "))  
y = int(input("Enter second number: "))  
print('The HCF of ',x,' and ',y ,'is ',computeHCF(x,y))

Enter first number: 54
Enter second number: 24
The HCF of  54  and  24 is  6


In [4]:
def solve(numheads,numlegs):
    ns='No solutions!'
    for i in range(numheads+1):
        j=numheads-i
        if 2*i+4*j==numlegs:
            return i,j
    return ns,ns

numheads=35
numlegs=94
solutions=solve(numheads,numlegs)
print(solutions)

(23, 12)


In [6]:
print("""this is a pyhton triple quote string
kjsdf 
 fksjf 
 lkgn """)

this is a pyhton triple quote string
kjsdf 
 fksjf 
 lkgn 


In [9]:
''' this is a comment
dskjfn'''

' this is a comment\ndskjfn'

In [12]:
print('this is \\n example')

this is \n example


In [38]:
print('this is \\t example')

this is \t example


In [155]:
def PrimeSeries(num):
    if num > 1:
        for i in range(2,int(num**0.5)+1):
            if num%i==0:
                print(num, 'not a prime number')
                break
        else:
            print(num, ' is a prime number')
    else:
        print(num, ' is not a prime number')
    NextNearestPrime(num)
    PreviousNearestPrime(num)
    return num

def NextNearestPrime(n):
    n=n+1
    l = [*range(n, (2*n)+1)]
    primes = []
    for i in l:
        if all([i % n for n in range(2, i)]):
            primes.append(i)
    print(min(primes),'is the next prime number')
    return min(primes)

def PreviousNearestPrime(n):
    #n=n-1
    l = [*range(2,n)]
    primes = []
    for i in l:
        if all([i % n for n in range(2, i)]):
            primes.append(i)
    print(max(primes),'is the previous prime number')
    return max(primes)

x=PrimeSeries(97)

97  is a prime number
101 is the next prime number
89 is the previous prime number


In [172]:
def PrimeSeries(num):
    if num > 1:
        for i in range(2,int(num**0.5)+1):
            if num%i==0:
                print(num, 'not a prime number')
                break
        else:
            print(num, ' is a prime number')
    else:
        print(num, ' is not a prime number')
        
    n=num
    l = [*range(2,n)]
    primes = []
    for i in l:
        if all([i % n for n in range(2, i)]):
            primes.append(i)
    print(max(primes),'is the previous prime number')

    n1=num+1
    l = [*range(n1, (2*n1)+1)]
    primes = []
    for i in l:
        if all([i % n1 for n1 in range(2, i)]):
            primes.append(i)
    print(min(primes),'is the next prime number')
    return num,max(primes),min(primes)
    

x=PrimeSeries(10)

10 not a prime number
7 is the previous prime number
11 is the next prime number


In [175]:
def PrimeSeries(num):
    if num > 1:
        for i in range(2,int(num**0.5)+1):
            if num%i==0:
                print(num, 'not a prime number')
                break
        else:
            print(num, ' is a prime number')
    else:
        print(num, ' is not a prime number')
    NextNearestPrime(num)
    PreviousNearestPrime(num)
    return num

def NextNearestPrime(n):
    n=n+1
    l = [*range(n, (2*n)+1)]
    primes = []
    for i in l:
        if all([i % n for n in range(2, i)]):
            primes.append(i)
    print(min(primes),'is the next prime number')
    return min(primes)

def PreviousNearestPrime(n):
    #n=n-1
    l = [*range(2,n)]
    primes = []
    for i in l:
        if all([i % n for n in range(2, i)]):
            primes.append(i)
    print(max(primes),'is the previous prime number')
    return max(primes)

x=PrimeSeries(97)

97  is a prime number
101 is the next prime number
89 is the previous prime number


In [193]:
#compare 2 strings and check which string is larger
String1=input('enter the first string')
String2=input('enter the second string')
a=[]
b=[]
for i in String1:
    a.append(i)
for j in String2:
    b.append(j)
if(len(a)>len(b)):
    print('String1 is larger')
elif(len(a)==len(b)):
     print('both the strings are equal')
else:
    print('String2 is larger')


enter the first stringashok
enter the second stringarun
String1 is larger


In [200]:
string1=input('enter 1st string')
string2=input('enter 2nd string')
if(string1==string2):
    print('string are equal')
elif(string1>=string2):
    print('string 1 is larger')
else:
    print('string 2 is larger')

enter 1st stringashok
enter 2nd stringarun
string 1 is larger


In [212]:
S=input('enter a string')
a=[]
b=[]
for i in S:
    if i.isdigit():
        a.append(i)
    if i.isalpha():
        b.append(i)
print(a)
print(b)
str1 = ''.join(a)
str2 = ''.join(b)
print(str1)
print(str2)

enter a stringsdlkfjnsdf54 fdslkfdsnf54 sdlkfnds35
['5', '4', '5', '4', '3', '5']
['s', 'd', 'l', 'k', 'f', 'j', 'n', 's', 'd', 'f', 'f', 'd', 's', 'l', 'k', 'f', 'd', 's', 'n', 'f', 's', 'd', 'l', 'k', 'f', 'n', 'd', 's']
545435
sdlkfjnsdffdslkfdsnfsdlkfnds


In [215]:
listOfCharac={}
a=input('enter characters')
for s in a:
    if s in listOfCharac.keys():
        listOfCharac[s]+=1
    else:
        listOfCharac[s]=1
print (listOfCharac)

enter characters65sd4f5sd4f68sdf435g15f4h3gf5h4gh
{'6': 2, '5': 5, 's': 3, 'd': 3, '4': 5, 'f': 5, '8': 1, '3': 2, 'g': 3, '1': 1, 'h': 3}


In [2]:
import pandas as pd
from pandas import Series

listOfCharac={}
a=input('enter a repeating sentence')
b=a.split(' ')
for s in b:
    if s in listOfCharac.keys():
        listOfCharac[s]+=1
    else:
        listOfCharac[s]=1
print (listOfCharac)

max1=max([i for i in listOfCharac.values()])
min1=min([i for i in listOfCharac.values()])
c=Series(listOfCharac)
print(c)
print(c.max())


enter a repeating sentenceashok si very good but he is very bad but ashok is ashok
{'ashok': 3, 'si': 1, 'very': 2, 'good': 1, 'but': 2, 'he': 1, 'is': 2, 'bad': 1}
ashok    3
si       1
very     2
good     1
but      2
he       1
is       2
bad      1
dtype: int64
3


In [1]:
import pandas as pd
from pandas import Series

listOfCharac={}
a=input('enter a repeating sentence')
b=a.split(' ')
for s in b:
    if s in listOfCharac.keys():
        listOfCharac[s]+=1
    else:
        listOfCharac[s]=1
print (listOfCharac)

maximum = max(listOfCharac, key=listOfCharac.get)  # Just use 'min' instead of 'max' for minimum.
print(maximum, listOfCharac[maximum])
minimum=min(listOfCharac, key=listOfCharac.get)
print(minimum, listOfCharac[minimum])

#c=Series(listOfCharac)
#print(c)
#print(c.max())


enter a repeating sentenceashok ashok ashok arun
{'ashok': 3, 'arun': 1}
ashok 3
arun 1


In [ ]:
#wap that accepts a sentence and calculates the number of letters and digits in sentence
a=input("enter a sentence")
b=c=0
for x in a:
    if x.isalpha():
        b=b+1
    elif x.isdigit():
        c=c+1
print(b)
print(c)


In [ ]:
#create a list which has elements like: 1*1,2*2,3*3......
#list comprehension
n=int(input("enter the value of n"))
a=list(range(n))
sq=[i*i for i in a]
print(sq)
    




In [ ]:
#rock scissor and paper
n=int(input("enter the loop no"))
player1=0;player2=0
print("rock=1,scissor=2,paper=3")
for data in range(0,n):
    p1=int(input())
    p2=int(input())
    if p1==1 and p2==2:
        palyer1+=1
    elif p1==1 and p2==3:
        player2+=1
    elif p1==2 and p2==3:
        player1+=1
    elif p1==2 and p2==1:
        player1+=1
    elif p1==3 and p2==1:
        player1+=1
    elif p1==3 and p2==2:
        player1+=1
    else:
        print("same inputs")
if(player1>player2):
    print("player1 wins")
else:
    print("player2 wins")
        

In [9]:
#fibonacci
n=int(input("no of terms"))
n1=0
n2=1
c=0
print("Fibonacci upto",n,":")
while(c<n):
    print(n1)
    n3=n1+n2
    n1=n2
    n2=n3
    c+=1

no of terms20
Fibonacci upto 20 :
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181


In [8]:
#fibonacci series
def fibonacci(nterms):
    n1=0
    n2=1
    Series=[n1,n2]
    for i in range(nterms-2):
        nth=n1+n2
        Series.append(nth)
        n1,n2=n2,nth
    return Series

Fibo=fibonacci(20)
print(Fibo)

   

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181]


In [1]:
#Write a a program to find the sum of first 50 natural numbers starting from 1
sum2=0
al=list(range(1,51))
for i in al:
    sum2+=i
print(sum2)

1275


In [2]:
#Write a program to to find the sum of all the numbers between 555 and 1111 which are divisible by 7
count=555
sum=0
d=list(range(555,1111))
for x in d:
    count+=1
    if(count%7==0):
        sum+=count
print(sum)

65807


In [4]:
#Write a program to to find the sum of all the numbers between 555 and 1111 which are divisible by 7 and not divisible by 5
count=555
sum=0
d=list(range(555,1111))
for x in d:
    count+=1
    if((count%7==0) & (count%5!=0)):
        sum+=count
print(sum)

52647


In [2]:
#Write a program to count the number of numbers between 555 and 1111 which are divisible by 7
count=0
d=list(range(555,1111))
for x in d:
    if(x%7==0):
        count=count+1
print(count)

79


In [6]:
#Write a program to compute the sum of squares of first 10 natural numbers
sum1=0
a=list(range(1,11))
s=[i*i for i in a]
print(s)
for k in s:
    sum1+=k
print(sum1)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
385


In [12]:
# Write a program to print the sum of squares of all the even numbers between 334 and 667
sum=0
a=list(range(334,667,2))
sq=[i*i for i in a]
for j in sq:
    sum+=j
print(sum)

43302432


In [17]:
#prime or not
import math
def isPrime(n):
    for i in range(2,int(math.sqrt(n)+1)):
        if n%i==0:
            return False
    return True

x=isPrime(11)
print(x)

True


In [19]:
#prime series
def PrimeSeries(nterms):
    Series=[]
    for i in range(2,nterms):
        nth=isPrime(i)
        if(nth):
            Series.append(i)
    return Series

Prime=PrimeSeries(int(input("enter number")))
print(Prime)

enter number20
[2, 3, 5, 7, 11, 13, 17, 19]


In [21]:
#prime range
def PrimeRange(begin=2,end=100):
    Series=[]
    for i in range(begin,end):
        nth=isPrime(i)
        if(nth):
            Series.append(i)
    return Series

Prime=PrimeRange(1,1000)
print(Prime)

[1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]


In [22]:
#print methods
numd=22
numh=0x21
numo=0o25
numb=0b10111
numf=25.67
str1="Windows"

print(numd,numh,numo,numb,numf,str1)
print("%d,%x,%o,%s,%f"%(numd,numd,numd,str1,numf))
print("%6d,%10s,%2.3f"%(numd,str1,numf)) #padding, precision

22 33 21 23 25.67 Windows
22,16,26,Windows,25.670000
    22,   Windows,25.670


In [24]:
#feet to inches
def f2i(feet):
    l=[]
    for i in feet:
        i=i*12
        l.append(i)
    return l
  
a=f2i([2,4,6,8,10])
print("list of inches ",a)

    

list of inches  [24, 48, 72, 96, 120]


In [25]:
#meters to centimeters
meters=[10,20,30,40,50,60]
cent=map(lambda M:M*100,meters)
print(type(cent),cent)
print(tuple(cent))

<class 'map'> <map object at 0x0000000004E34588>
(1000, 2000, 3000, 4000, 5000, 6000)


In [27]:
#check if a string is a palindrome or not
def palindrome(str):
    start=str[:]
    reverse=str[::-1]
    if(start==reverse):
        print("its a palindrome")
    else:
        print("not a palindrome")
        
x=palindrome("maam")

its a palindrome


In [ ]:
#excercise
import re
def A(sentence):
    a=[]
    l1=[]
    newdt=sentence.split(' ')
    l1.append(newdt)
    print()
    print("splitting sentence into words")
    print(l1)
    print()
    B(l1)
    return l1


def B(l1):
    for i in l1:
        r = re.compile(".*[0-9]")
        newlist = list(filter(r.match,i))
        print("extrating numbers, in case of presence of any special char that is also extracted")
        print(newlist)
        print()
        C(newlist)
    return newlist
        
def C(newlist):
    a=[]
    nl=[]
    for j in newlist:
        r=re.compile(".*[0-9]")
        nl=list(filter(r.match,j))
        a+=nl
    D(a)
    return a

def D(a):
    print("The extracted numers are :")
    print(a)

x=A(input("enter sentence "))




In [1]:
#sudoku
import numpy as np

c=[[0,4,0,1],[3,0,4,0],[1,0,0,4],[0,2,1,0]]
matrix=np.array(c)
print(matrix)

def mat(lis):
    for lis_1 in lis:
        for row in range(0,4):
            for col in range(0,4):
                if lis_1 not in matrix[row] and lis_1 not in matrix[:,col]:
                    if matrix[row,col]==0:
                        matrix[row,col]=lis_1
    return matrix
lis=list(range(1,5))
print(mat(lis))

[[0 4 0 1]
 [3 0 4 0]
 [1 0 0 4]
 [0 2 1 0]]
[[2 4 3 1]
 [3 1 4 2]
 [1 3 2 4]
 [4 2 1 3]]


In [1]:
# to find the factorial of a number:
def fact_no(n):
    if (n==0 or n==1):
        return 1
    else:
        return n*fact_no(n-1)
    
x=fact_no(int(input('enter the number')))
print('The factorial is',x)


enter the number5
The factorial is 120


In [9]:
# to find the simple interest:
p=float(input('Enter the principle amount:'))
r=float(input('enter the rate:'))
t=float(input('Enter the time in years'))

def si(p,r,t):
    si_no=float((p*r*t)/100)
    return si_no

k=si(p,r,t)
print(k)


Enter the principle amount:10000
enter the rate:5
Enter the time in years3
1500.0


In [1]:
# to check if the number is armstrong or not:
#An Armstrong number of three digits is an integer such that the sum of the cubes of 
#its digits is equal to the number itself. For example, 371 is an Armstrong number since 3**3 + 7**3 + 1**3 = 371.


#Armstrong number 1: 0
#Armstrong number 2: 1
#Armstrong number 3: 153
#Armstrong number 4: 370
#Armstrong number 5: 371
#Armstrong number 6: 407

num = int(input("Enter a number: "))
sum = 0
temp = num

while temp > 0:
    digit = temp % 10
    sum += digit ** 3
    temp //= 10

if num == sum:
    print(num,"is an Armstrong number")
else:
    print(num,"is not an Armstrong number") 

Enter a number: 5
5 is not an Armstrong number


In [ ]:
#Find Armstrong Number in an Interval
# Program to check Armstrong numbers in certain interval

lower = 100
upper = 2000

# To take input from the user
# lower = int(input("Enter lower range: "))
# upper = int(input("Enter upper range: "))

for num in range(lower, upper + 1):
    order = len(str(num))
    sum = 0
    temp = num
while temp > 0:
    digit = temp % 10
    sum += digit ** order
    temp //= 1
if num == sum:
    print(num)

In [ ]:
#largest among 3 numbers

num1 = 10
num2 = 16
num3 = 15


if (num1 >= num2) and (num1 >= num3):
    largest = num1
elif (num2 >= num1) and (num2 >= num3):
    largest = num2
else:
    largest = num3

print("The largest number between",num1,",",num2,"and",num3,"is",largest)

In [41]:
#Check if a Number is Positive, Negative or 0
num = float(input("Enter a number: "))
if num > 0:
    print("Positive number")
elif num == 0:
    print("Zero")
else:
    print("Negative number")

Enter a number: 5
Positive number


In [10]:
#harshad number
#if a number is divisible by the sum of its digits, then it will be known as a Harshad Number.

#For example:

#The number 156 is divisible by the sum (12) of its digits (1, 5, 6 ).

#Some Harshad numbers are 8, 54, 120, etc.
num = 12;    
rem = sum = 0;    
     
#Make a copy of num and store it in variable n    
n = num;    
     
#Calculates sum of digits    
while(num > 0):    
    rem = num%10;    
    sum = sum + rem;    
    num = num//10;    
     
#Checks whether the number is divisible by the sum of digits    
if(n%sum == 0):    
    print(str(n) + " is a harshad number");    
else:    
    print(str(n) + " is not a harshad number"); 

12 is a harshad number
