In [12]:
a=list(range(17,171,17))

In [13]:
a

[17, 34, 51, 68, 85, 102, 119, 136, 153, 170]

In [15]:
type(a)

list

In [20]:
a=5
Area=5
print("Area=",a)

Area= 5


In [60]:
for i in range(1,10):
    print("inverse of",i,"is",1/i)

inverse of 1 is 1.0
inverse of 2 is 0.5
inverse of 3 is 0.3333333333333333
inverse of 4 is 0.25
inverse of 5 is 0.2
inverse of 6 is 0.16666666666666666
inverse of 7 is 0.14285714285714285
inverse of 8 is 0.125
inverse of 9 is 0.1111111111111111


In [59]:
dict1={'a':2,'b':3,'c':4}
l1=[]
for i,j in dict1.items():
    l1.append(i)
    l1.append(j)
print(l1)
type(a)


['a', 2, 'b', 3, 'c', 4]


list

In [65]:
dict1={'a':2,'b':3,'c':4}
l1=[]
for i,j in dict1.items():
    l1.extend([i,j])
print(l1)

['a', 2, 'b', 3, 'c', 4]


In [67]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [69]:
list("Ashok")

['A', 's', 'h', 'o', 'k']

In [77]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [99]:
A=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])

In [92]:
A

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
A.reshape(3,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [117]:
arr=np.arange(24).reshape(4,3,2) #depth,row,col
arr

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [118]:
arr[0]

array([[0, 1],
       [2, 3],
       [4, 5]])

In [122]:
arr1=np.arange(25).reshape(5,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
arr1[2:4,2:4]

array([[12, 13],
       [17, 18]])

In [156]:
arr1[:,1:2]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [154]:
arr1[:,[1]]

array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])

In [168]:
ary1=np.arange(6).reshape(2,3)
ary2=ary1.T

In [174]:
ary1

array([[0, 1, 2],
       [3, 4, 5]])

In [175]:
ary2

array([[0, 3],
       [1, 4],
       [2, 5]])

In [180]:
ary3=np.dot(ary1,ary2)

In [182]:
ary3

array([[ 5, 14],
       [14, 50]])

In [184]:
ary4=np.arange(9).reshape(3,3)

In [186]:
ary4.mean()

4.0

In [189]:
ary4.mean(0)#col wise mean only in numpy

array([3., 4., 5.])

In [191]:
ary4.mean(1)#row wise mean only in numpy

array([1., 4., 7.])

In [220]:
#where function
A1=np.array([1,2,3])
A2=np.array([100,200,300])
A3=np.array([True,False,True])

In [209]:
A1

array([1, 2, 3])

In [211]:
A2

array([100, 200, 300])

In [213]:
A3

array([ True, False,  True])

In [221]:
np.where(A3,A1,A2)

array([  1, 200,   3])

In [222]:
#where(condition,True,False)

In [227]:
A4=np.array([1,2,3,4]).reshape(2,2)
A5=np.array([10,20,30,40]).reshape(2,2)
A6=np.array([True,True,False,False]).reshape(2,2)

In [229]:
A4

array([[1, 2],
       [3, 4]])

In [231]:
A5

array([[10, 20],
       [30, 40]])

In [233]:
A6

array([[ True,  True],
       [False, False]])

In [236]:
np.where(A6,A4,A5)

array([[ 1,  2],
       [30, 40]])