In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [4]:
#merge

In [2]:
d1=DataFrame({'Data1':[0,1,2,3,4,5],'key':['X','Z','Y','Z','X','X']})

In [3]:
d1


Data1 key
0      0   X
1      1   Z
2      2   Y
3      3   Z
4      4   X
5      5   X

In [4]:
d2=DataFrame({'Data1':[1,2,3],'key':['Q','Y','Z']})

In [11]:
d2

Data1 key
0      1   Q
1      2   Y
2      3   Z

In [13]:
 #f1)irst type of merge
    pd.merge(d1,d2) #merging on common columns

Data1 key
0      2   Y
1      3   Z

In [16]:
 pd.merge(d1,d2,on='key')#will take common key values

Data1_x key  Data1_y
0        1   Z        3
1        3   Z        3
2        2   Y        2

In [5]:
pd.merge(d1,d2,how='left')#left join ,left hand side of d1 will be der 

Data1 key
0      0   X
1      1   Z
2      2   Y
3      3   Z
4      4   X
5      5   X

In [6]:
pd.merge(d1,d2,how='right')

Data1 key
0      2   Y
1      3   Z
2      1   Q

In [7]:
pd.merge(d1,d2,how='outer')#all the keys from left and right

Data1 key
0      0   X
1      1   Z
2      2   Y
3      3   Z
4      4   X
5      5   X
6      1   Q

In [33]:
d3=DataFrame({'Data1':[0,1,2,3,4,5],'key':['X','X','X','Y','Z','Z']})

In [34]:
d4=DataFrame({'Data2':[0,1,2,3,4],'key':['Y','Y','Z','Z','X']})

In [35]:
d3

Data1 key
0      0   X
1      1   X
2      2   X
3      3   Y
4      4   Z
5      5   Z

In [36]:
d4

Data2 key
0      0   Y
1      1   Y
2      2   Z
3      3   Z
4      4   X

In [39]:
pd.merge(d3,d4)

Data1 key  Data2
0      0   X      4
1      1   X      4
2      2   X      4
3      3   Y      0
4      3   Y      1
5      4   Z      2
6      4   Z      3
7      5   Z      2
8      5   Z      3

In [40]:
#2)second type of merge

In [43]:
d5=DataFrame({'Data1':[0,1,2,3,4],'key':['X','X','Y','Y','Z']})

In [49]:
d6=DataFrame({'GData':[10,20]},index=['X','X'])

In [47]:
d5

Data1 key
0      0   X
1      1   X
2      2   Y
3      3   Y
4      4   Z

In [51]:
d6

GData
X     10
X     20

In [55]:
pd.merge(d5,d6,left_on='key',right_index=True,how='outer')#keep d5 on left #left_on=''#name of the column which we want to match
#right_index=true

Data1 key  GData
0      0   X   10.0
0      0   X   20.0
1      1   X   10.0
1      1   X   20.0
2      2   Y    NaN
3      3   Y    NaN
4      4   Z    NaN

In [58]:
pd.merge(d5,d6,left_on='key',right_index=True)#left_on -> take column of left dataset column mentioning

Data1 key  GData
0      0   X     10
0      0   X     20
1      1   X     10
1      1   X     20

In [59]:
#right_on=''
#right_index=True

In [60]:
#concatenate

In [62]:
A=np.arange(9).reshape(3,3)

In [64]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [66]:
np.concatenate([A,A])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
np.concatenate([A,A],axis=1)#col wise #opp to pandas

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [71]:
ser1=Series([3,4,5],index=list('tuv'))

In [73]:
ser2=Series([3,5],index=list('xy'))

In [74]:
ser1

t    3
u    4
v    5
dtype: int64

In [75]:
ser2

x    3
y    5
dtype: int64

In [77]:
pd.concat([ser1,ser2])

t    3
u    4
v    5
x    3
y    5
dtype: int64

In [121]:
pd.concat([ser1,ser2],axis=1)#will get dataframe, never do this

C:\Users\Ashok\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
t  3.0  NaN
u  4.0  NaN
v  5.0  NaN
x  NaN  3.0
y  NaN  5.0

In [80]:
#combining

In [81]:
#combine_first same as where function without giving any condition

In [83]:
ser3=Series([2,np.nan,4,np.nan,6],index=list('ABCDE'))

In [85]:
ser3

A    2.0
B    NaN
C    4.0
D    NaN
E    6.0
dtype: float64

In [87]:
ser4=Series([0,1,2,3,4],index=list('ABCDE'))

In [89]:
ser4

A    0
B    1
C    2
D    3
E    4
dtype: int64

In [91]:
ser3.combine_first(ser4)#workd for dataframe as well

A    2.0
B    1.0
C    4.0
D    3.0
E    6.0
dtype: float64

In [92]:
#rename

In [97]:
df1=DataFrame({'A':[0,4,8],'B':[1,5,9],'C':[2,6,10],'D':[3,7,11]},index=['NY','LA','GRG'])#do this using array also
#

In [99]:
df1

A  B   C   D
NY   0  1   2   3
LA   4  5   6   7
GRG  8  9  10  11

In [102]:
df1.rename({'NY':'NewYork'})#change ny,la,grg

A  B   C   D
NewYork  0  1   2   3
LA       4  5   6   7
GRG      8  9  10  11

In [105]:
df1.rename({'A':'Alpha'},axis=1,inplace=True)

In [107]:
df1

Alpha  B   C   D
NY       0  1   2   3
LA       4  5   6   7
GRG      8  9  10  11

In [124]:
df1.rename(index={'LA':'LasVegas'},columns={'B':'beta'},inplace=True)#both row and column

Alpha  beta   C   D
NY            0     1   2   3
LasVegas      4     5   6   7
GRG           8     9  10  11

In [125]:
df1

Alpha  beta   C   D
NY            0     1   2   3
LasVegas      4     5   6   7
GRG           8     9  10  11

In [128]:
df=DataFrame({'Functions':['drop','dropna','replace','rename','isnull','notnull','reindex','sort_index','sort_values','rank','swaplevel','sortlevel','fillna','combine_first','concat','merge'],
             'Inplace?':[1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]})

In [129]:
df

Functions  Inplace?
0            drop         1
1          dropna         1
2         replace         1
3          rename         1
4          isnull         0
5         notnull         0
6         reindex         0
7      sort_index         0
8     sort_values         0
9            rank         0
10      swaplevel         0
11      sortlevel         0
12         fillna         0
13  combine_first         0
14         concat         0
15          merge         0