In [2]:
import numpy             as np
import pandas            as pd
import scipy.stats       as stats
import matplotlib.pyplot as plt

In [62]:
#coin toss
p=0.5
n=2
k=np.arange(0,3)

In [63]:
binomial = stats.binom.pmf(k,n,p)

In [64]:
binomial

array([0.25, 0.5 , 0.25])

In [65]:
cumbinomial = stats.binom.cdf(k,n,p)

In [66]:
cumbinomial

array([0.25, 0.75, 1.  ])

In [43]:
#orders
p=0.868
n=3
k=np.arange(0,4)

In [44]:
binomial1 = stats.binom.pmf(k,n,p)

In [45]:
binomial1

array([0.00229997, 0.0453721 , 0.2983559 , 0.65397203])

In [46]:
cumbinomial1 = stats.binom.cdf(k,n,p)

In [49]:
cumbinomial1

array([0.00229997, 0.04767206, 0.34602797, 1.        ])

In [50]:
#credit card
p=0.6
n=7
k=np.arange(0,8)

In [53]:
binomial1 = stats.binom.pmf(k,n,p)

In [55]:
binomial1

array([0.0016384, 0.0172032, 0.0774144, 0.193536 , 0.290304 , 0.2612736,
       0.1306368, 0.0279936])

In [57]:
cumbinomial1 = stats.binom.cdf(k,n,p)

In [67]:
cumbinomial1

array([0.0016384, 0.0188416, 0.096256 , 0.289792 , 0.580096 , 0.8413696,
       0.9720064, 1.       ])

In [8]:
import pandas as pd
a=pd.DataFrame([4, 17, 9, 11, 26, 11, 13, 7, 22, 11])
a.describe()

0
count  10.000000
mean   13.100000
std     6.756889
min     4.000000
25%     9.500000
50%    11.000000
75%    16.000000
max    26.000000